HEADERS += \
    ../../jni/facedetector/conf/b_BasicEm/LibConfig.h \
    ../../jni/facedetector/b_TensorEm/VectorMap.h \
    ../../jni/facedetector/b_TensorEm/Uint32Rect.h \
    ../../jni/facedetector/b_TensorEm/SubVecMap.h \
    ../../jni/facedetector/b_TensorEm/RBFMap2D.h \
    ../../jni/facedetector/b_TensorEm/Normalizer.h \
    ../../jni/facedetector/b_TensorEm/Mat.h \
    ../../jni/facedetector/b_TensorEm/MapSequence.h \
    ../../jni/facedetector/b_TensorEm/Int32Mat.h \
    ../../jni/facedetector/b_TensorEm/Int16Vec3D.h \
    ../../jni/facedetector/b_TensorEm/Int16Vec2D.h \
    ../../jni/facedetector/b_TensorEm/Int16Rect.h \
    ../../jni/facedetector/b_TensorEm/Int16Mat2D.h \
    ../../jni/facedetector/b_TensorEm/IdCluster2D.h \
    ../../jni/facedetector/b_TensorEm/Functions.h \
    ../../jni/facedetector/b_TensorEm/Flt16Vec3D.h \
    ../../jni/facedetector/b_TensorEm/Flt16Vec2D.h \
    ../../jni/facedetector/b_TensorEm/Flt16Vec.h \
    ../../jni/facedetector/b_TensorEm/Flt16Mat3D.h \
    ../../jni/facedetector/b_TensorEm/Flt16Mat2D.h \
    ../../jni/facedetector/b_TensorEm/Flt16Alt3D.h \
    ../../jni/facedetector/b_TensorEm/Flt16Alt2D.h \
    ../../jni/facedetector/b_TensorEm/CompactMat.h \
    ../../jni/facedetector/b_TensorEm/CompactAlt.h \
    ../../jni/facedetector/b_TensorEm/Cluster3D.h \
    ../../jni/facedetector/b_TensorEm/Cluster2D.h \
    ../../jni/facedetector/b_TensorEm/Alt.h \
    ../../jni/facedetector/b_ImageEm/UInt32Image.h \
    ../../jni/facedetector/b_ImageEm/UInt16BytePyrImage.h \
    ../../jni/facedetector/b_ImageEm/UInt16ByteImage.h \
    ../../jni/facedetector/b_ImageEm/UInt8PyramidalImage.h \
    ../../jni/facedetector/b_ImageEm/UInt8Image.h \
    ../../jni/facedetector/b_ImageEm/HistoEq16.h \
    ../../jni/facedetector/b_ImageEm/HistoEq.h \
    ../../jni/facedetector/b_ImageEm/Functions.h \
    ../../jni/facedetector/b_ImageEm/Flt16Image.h \
    ../../jni/facedetector/b_ImageEm/ComplexImage.h \
    ../../jni/facedetector/b_ImageEm/APhImage.h \
    ../../jni/facedetector/b_BitFeatureEm/Sequence.h \
    ../../jni/facedetector/b_BitFeatureEm/Scanner.h \
    ../../jni/facedetector/b_BitFeatureEm/ScanDetector.h \
    ../../jni/facedetector/b_BitFeatureEm/LocalScanner.h \
    ../../jni/facedetector/b_BitFeatureEm/LocalScanDetector.h \
    ../../jni/facedetector/b_BitFeatureEm/L06DnsNx4x4Ftr.h \
    ../../jni/facedetector/b_BitFeatureEm/L06Dns4x4Ftr.h \
    ../../jni/facedetector/b_BitFeatureEm/L06Dns3x3Ftr.h \
    ../../jni/facedetector/b_BitFeatureEm/L04Tld2x4Ftr.h \
    ../../jni/facedetector/b_BitFeatureEm/L04Dns3x3Ftr.h \
    ../../jni/facedetector/b_BitFeatureEm/L04Dns2x4Ftr.h \
    ../../jni/facedetector/b_BitFeatureEm/L04Dns2x2Ftr.h \
    ../../jni/facedetector/b_BitFeatureEm/L01Tld2x4Ftr.h \
    ../../jni/facedetector/b_BitFeatureEm/L01Tld1x1Ftr.h \
    ../../jni/facedetector/b_BitFeatureEm/L01Dns2x4Ftr.h \
    ../../jni/facedetector/b_BitFeatureEm/I04Tld2x4Ftr.h \
    ../../jni/facedetector/b_BitFeatureEm/I04Dns2x4Ftr.h \
    ../../jni/facedetector/b_BitFeatureEm/I04Dns2x2Ftr.h \
    ../../jni/facedetector/b_BitFeatureEm/Functions.h \
    ../../jni/facedetector/b_BitFeatureEm/Feature.h \
    ../../jni/facedetector/b_BitFeatureEm/BitParam.h \
    ../../jni/facedetector/b_BasicEm/UInt32Arr.h \
    ../../jni/facedetector/b_BasicEm/UInt16Arr.h \
    ../../jni/facedetector/b_BasicEm/UInt8Arr.h \
    ../../jni/facedetector/b_BasicEm/String.h \
    ../../jni/facedetector/b_BasicEm/Phase.h \
    ../../jni/facedetector/b_BasicEm/MemTbl.h \
    ../../jni/facedetector/b_BasicEm/MemSeg.h \
    ../../jni/facedetector/b_BasicEm/Memory.h \
    ../../jni/facedetector/b_BasicEm/Math.h \
    ../../jni/facedetector/b_BasicEm/Int32Arr.h \
    ../../jni/facedetector/b_BasicEm/Int16Arr.h \
    ../../jni/facedetector/b_BasicEm/Int8Arr.h \
    ../../jni/facedetector/b_BasicEm/Functions.h \
    ../../jni/facedetector/b_BasicEm/DynMemManager.h \
    ../../jni/facedetector/b_BasicEm/Context.h \
    ../../jni/facedetector/b_BasicEm/Config.h \
    ../../jni/facedetector/b_BasicEm/ComplexArr.h \
    ../../jni/facedetector/b_BasicEm/Complex.h \
    ../../jni/facedetector/b_BasicEm/Basic.h \
    ../../jni/facedetector/b_BasicEm/APhArr.h \
    ../../jni/facedetector/b_BasicEm/APh.h \
    ../../jni/facedetector/b_APIEm/Types.h \
    ../../jni/facedetector/b_APIEm/Functions.h \
    ../../jni/facedetector/b_APIEm/FaceFinderRef.h \
    ../../jni/facedetector/b_APIEm/FaceFinder.h \
    ../../jni/facedetector/b_APIEm/DCR.h \
    ../../jni/facedetector/b_APIEm/BFFaceFinder.h \
    ../../jni/facedetector/Types.h \
    ../../jni/facedetector/SDK_Internal.h \
    ../../jni/facedetector/SDK.h \
    ../../jni/facedetector/fd_emb_sdk.h \
    ../../jni/facedetector/FaceFinder_Internal.h \
    ../../jni/facedetector/FaceFinder.h \
    ../../jni/facedetector/DCR_Internal.h \
    ../../jni/facedetector/DCR.h

SOURCES += \
    ../../jni/facedetector/b_TensorEm/VectorMap.c \
    ../../jni/facedetector/b_TensorEm/Uint32Rect.c \
    ../../jni/facedetector/b_TensorEm/SubVecMap.c \
    ../../jni/facedetector/b_TensorEm/RBFMap2D.c \
    ../../jni/facedetector/b_TensorEm/Normalizer.c \
    ../../jni/facedetector/b_TensorEm/Mat.c \
    ../../jni/facedetector/b_TensorEm/MapSequence.c \
    ../../jni/facedetector/b_TensorEm/Int32Mat.c \
    ../../jni/facedetector/b_TensorEm/Int16Vec3D.c \
    ../../jni/facedetector/b_TensorEm/Int16Vec2D.c \
    ../../jni/facedetector/b_TensorEm/Int16Rect.c \
    ../../jni/facedetector/b_TensorEm/Int16Mat2D.c \
    ../../jni/facedetector/b_TensorEm/IdCluster2D.c \
    ../../jni/facedetector/b_TensorEm/Functions.c \
    ../../jni/facedetector/b_TensorEm/Flt16Vec3D.c \
    ../../jni/facedetector/b_TensorEm/Flt16Vec2D.c \
    ../../jni/facedetector/b_TensorEm/Flt16Vec.c \
    ../../jni/facedetector/b_TensorEm/Flt16Mat3D.c \
    ../../jni/facedetector/b_TensorEm/Flt16Mat2D.c \
    ../../jni/facedetector/b_TensorEm/Flt16Alt3D.c \
    ../../jni/facedetector/b_TensorEm/Flt16Alt2D.c \
    ../../jni/facedetector/b_TensorEm/CompactMat.c \
    ../../jni/facedetector/b_TensorEm/CompactAlt.c \
    ../../jni/facedetector/b_TensorEm/Cluster3D.c \
    ../../jni/facedetector/b_TensorEm/Cluster2D.c \
    ../../jni/facedetector/b_TensorEm/Alt.c \
    ../../jni/facedetector/b_ImageEm/UInt32Image.c \
    ../../jni/facedetector/b_ImageEm/UInt16BytePyrImage.c \
    ../../jni/facedetector/b_ImageEm/UInt16ByteImage.c \
    ../../jni/facedetector/b_ImageEm/UInt8PyramidalImage.c \
    ../../jni/facedetector/b_ImageEm/UInt8Image.c \
    ../../jni/facedetector/b_ImageEm/HistoEq16.c \
    ../../jni/facedetector/b_ImageEm/HistoEq.c \
    ../../jni/facedetector/b_ImageEm/Functions.c \
    ../../jni/facedetector/b_ImageEm/Flt16Image.c \
    ../../jni/facedetector/b_ImageEm/ComplexImage.c \
    ../../jni/facedetector/b_ImageEm/APhImage.c \
    ../../jni/facedetector/b_BitFeatureEm/Sequence.c \
    ../../jni/facedetector/b_BitFeatureEm/Scanner.c \
    ../../jni/facedetector/b_BitFeatureEm/ScanDetector.c \
    ../../jni/facedetector/b_BitFeatureEm/LocalScanner.c \
    ../../jni/facedetector/b_BitFeatureEm/LocalScanDetector.c \
    ../../jni/facedetector/b_BitFeatureEm/L06DnsNx4x4Ftr.c \
    ../../jni/facedetector/b_BitFeatureEm/L06Dns4x4Ftr.c \
    ../../jni/facedetector/b_BitFeatureEm/L06Dns3x3Ftr.c \
    ../../jni/facedetector/b_BitFeatureEm/L04Tld2x4Ftr.c \
    ../../jni/facedetector/b_BitFeatureEm/L04Dns3x3Ftr.c \
    ../../jni/facedetector/b_BitFeatureEm/L04Dns2x4Ftr.c \
    ../../jni/facedetector/b_BitFeatureEm/L04Dns2x2Ftr.c \
    ../../jni/facedetector/b_BitFeatureEm/L01Tld2x4Ftr.c \
    ../../jni/facedetector/b_BitFeatureEm/L01Tld1x1Ftr.c \
    ../../jni/facedetector/b_BitFeatureEm/L01Dns2x4Ftr.c \
    ../../jni/facedetector/b_BitFeatureEm/I04Tld2x4Ftr.c \
    ../../jni/facedetector/b_BitFeatureEm/I04Dns2x4Ftr.c \
    ../../jni/facedetector/b_BitFeatureEm/I04Dns2x2Ftr.c \
    ../../jni/facedetector/b_BitFeatureEm/Functions.c \
    ../../jni/facedetector/b_BitFeatureEm/Feature.c \
    ../../jni/facedetector/b_BitFeatureEm/BitParam.c \
    ../../jni/facedetector/b_BasicEm/UInt32Arr.c \
    ../../jni/facedetector/b_BasicEm/UInt16Arr.c \
    ../../jni/facedetector/b_BasicEm/UInt8Arr.c \
    ../../jni/facedetector/b_BasicEm/String.c \
    ../../jni/facedetector/b_BasicEm/Phase.c \
    ../../jni/facedetector/b_BasicEm/MemTbl.c \
    ../../jni/facedetector/b_BasicEm/MemSeg.c \
    ../../jni/facedetector/b_BasicEm/Memory.c \
    ../../jni/facedetector/b_BasicEm/MathSSE2.c \
    ../../jni/facedetector/b_BasicEm/Math.c \
    ../../jni/facedetector/b_BasicEm/Int32Arr.c \
    ../../jni/facedetector/b_BasicEm/Int16Arr.c \
    ../../jni/facedetector/b_BasicEm/Int8Arr.c \
    ../../jni/facedetector/b_BasicEm/Functions.c \
    ../../jni/facedetector/b_BasicEm/DynMemManager.c \
    ../../jni/facedetector/b_BasicEm/Context.c \
    ../../jni/facedetector/b_BasicEm/ComplexArr.c \
    ../../jni/facedetector/b_BasicEm/Complex.c \
    ../../jni/facedetector/b_BasicEm/APhArr.c \
    ../../jni/facedetector/b_BasicEm/APh.c \
    ../../jni/facedetector/b_APIEm/Functions.c \
    ../../jni/facedetector/b_APIEm/FaceFinderRef.c \
    ../../jni/facedetector/b_APIEm/FaceFinder.c \
    ../../jni/facedetector/b_APIEm/DCR.c \
    ../../jni/facedetector/b_APIEm/BFFaceFinder.c \
    ../../jni/facedetector/SDK.c \
    ../../jni/facedetector/FaceFinder.c \
    ../../jni/facedetector/DCR.c

INCLUDEPATH += ../../jni/facedetector
